name: goat_player
description: Same good old Better Player but it will get updated and fixed and remain GOAT.
version: 0.0.2

homepage: https://github.com/akashefrath/goat_player
documentation: https://jhomlala.github.io/betterplayer/

environment:
  sdk: '>=2.15.0 <4.0.0'
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  wakelock_plus: ^1.1.4
  meta: ^1.7.0
  flutter_widget_from_html_core: ^0.14.11
  visibility_detector: ^0.4.0+2
  path_provider: ^2.0.10
  collection: ^1.16.0
  xml: ^6.1.0

dev_dependencies:
  lint: ^2.3.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.goat.player
        pluginClass: GoatPlayerPlugin
      ios:
        pluginClass: GoatVideoPlayerPlugin